Repository karthikbalasubramani/connectify, pull requests merged in 2023-07, with the labels that each got.

#18 Modified User Update API and Login API
  .env
  .gitignore
  constants.py
  models/user_model.py
  mutation/user_mutation.py
  query/user_query.py
  tests/test_user.py
Labels: enhancement

#20 Develop update api testcases
  models/user_model.py
  tests/common/user_common.py
  tests/test_user.py
  tests/testdata/user_testcases.json
Labels: TestCase Enhancement, TestCase Development

#22 Developed Reset password api and Modification in Models
  models/user_model.py
  mutation/user_mutation.py
  tests/common/user_common.py
  tests/test_user.py
Labels: Feature Development, Feature Enhancement

#24 Reset password api testcases
  .github/workflows/main.yaml
  mutation/user_mutation.py
  tests/common/user_common.py
  tests/test_user.py
  tests/testdata/user_testcases.json
Labels: Feature Enhancement, TestCase Development

#25 Posting a new tweet API and testcase for that
  constants.py
  main.py
  models/tweet_model.py
  mutation/tweet_mutation.py
  mutation/user_mutation.py
  tests/common/tweet_common.py
  tests/common/user_common.py
  tests/test_tweet.py
  tests/testdata/tweet_testcases.json
Labels: Feature Development, TestCase Development

#26 Get all my tweets api and testcases
  .github/workflows/main.yaml
  main.py
  models/tweet_model.py
  query/tweet_query.py
  query/user_query.py
  tests/common/tweet_common.py
  tests/test_tweet.py
  tests/testdata/tweet_testcases.json
Labels: Feature Development, Feature Enhancement, TestCase Development

#27 Get single tweet API and TestCase for that
  models/tweet_model.py
  query/tweet_query.py
  tests/common/tweet_common.py
  tests/test_tweet.py
Labels: Feature Development, TestCase Development

#28 Delete-single-tweet and Delete-all-user-tweets API's and testcases
  constants.py
  models/tweet_model.py
  mutation/tweet_mutation.py
  tests/common/tweet_common.py
  tests/test_tweet.py
  tests/testdata/tweet_testcases.json
Labels: Feature Development, TestCase Development

#29 Development of Tweets Module with testcases
  .github/workflows/main.yaml
  constants.py
  main.py
  models/tweet_model.py
  mutation/tweet_mutation.py
  mutation/user_mutation.py
  query/tweet_query.py
  query/user_query.py
  tests/common/tweet_common.py
  tests/common/user_common.py
  tests/test_tweet.py
  tests/test_user.py
  tests/testdata/tweet_testcases.json
  tests/testdata/user_testcases.json
Labels: Verified And Merged

#30 adding LIKE feature and testcase for that
  .github/workflows/main.yaml
  constants.py
  main.py
  models/tweet_model.py
  models/user_model.py
  mutation/likes_mutation.py
  mutation/tweet_mutation.py
  mutation/user_mutation.py
  query/tweet_query.py
  templates/login.html
  templates/static/script.js
  templates/static/styles.css
  templates/tweets.html
  tests/common/test_utility.py
  tests/common/tweet_common.py
  tests/common/user_common.py
  tests/test_like.py
  tests/test_tweet.py
  tests/test_user.py
  tests/testdata/like_testcases.json
  tests/testdata/user_testcases.json
Labels: Feature Development, TestCase Enhancement, TestCase Development

#31 Get-all-tweets and single-tweet model response
  main.py
  models/tweet_model.py
  models/user_model.py
  query/tweet_query.py
Labels: Feature Enhancement

#32 Development of like-dislike Features and testcases for that, modified response get-single-tweet and get all tweets
  .github/workflows/main.yaml
  constants.py
  main.py
  models/tweet_model.py
  models/user_model.py
  mutation/likes_mutation.py
  mutation/tweet_mutation.py
  mutation/user_mutation.py
  query/tweet_query.py
  templates/login.html
  templates/static/script.js
  templates/static/styles.css
  templates/tweets.html
  tests/common/test_utility.py
  tests/common/tweet_common.py
  tests/common/user_common.py
  tests/test_like.py
  tests/test_tweet.py
  tests/test_user.py
  tests/testdata/like_testcases.json
  tests/testdata/user_testcases.json
Labels: Verified And Merged

#34 Comment Add Feature and testcase for that
  main.py
  models/tweet_model.py
  mutation/comment_mutation.py
  mutation/tweet_mutation.py
  query/tweet_query.py
  tests/test_comment.py
Labels: Feature Development, TestCase Development

#35 update/delete comment and modifications in getTweet API
  .github/workflows/main.yaml
  models/comment_model.py
  models/tweet_model.py
  mutation/comment_mutation.py
  mutation/tweet_mutation.py
  query/tweet_query.py
  tests/test_comment.py
  tests/test_tweet.py
Labels: Feature Development, Feature Enhancement, TestCase Development
